---
  - name: Get Zabbix Package
    command: rpm -ivh http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm

  - name: Install Zabbix Agent
    yum: 
      name: zabbix-agent
      state: present

  - name: Configure Zabbix Agent
    template:
      src: zabbix_agent.conf
      dest: /etc/zabbix/zabbix_agent.conf
    notify: restart zabbix-agent

  - name: Start Zabbix Agent service
    service:
      name: zabbix-agent
      state: started
